spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    hikari:
      username: root
      password: root
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
