version: '3.4'

services:
  db:
    container_name: USERS
    image: postgres:latest
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - data:/var/lib/postgres
      - ./init.sql:/init.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  data: